import logging

keycode_conversion = {
    1: 'esc',
    2: '1',
    3: '2',
    4: '3',
    5: '4',
    6: '5',
    7: '6',
    8: '7',
    9: '8',
    10: '9',
    11: '0',
    12: 'minus',
    13: 'equal',
    14: 'backspace',
    15: 'tab',
    16: 'q',
    17: 'w',
    18: 'e',
    19: 'r',
    20: 't',
    21: 'y',
    22: 'u',
    23: 'i',
    24: 'o',
    25: 'p',
    26: 'leftbrace',
    27: 'rightbrace',
    28: 'enter',
    29: 'leftctrl',
    30: 'a',
    31: 's',
    32: 'd',
    33: 'f',
    34: 'g',
    35: 'h',
    36: 'j',
    37: 'k',
    38: 'l',
    39: 'semicolon',
    40: 'apostrophe',
    41: 'grave',
    42: 'leftshift',
    43: 'backslash',
    44: 'z',
    45: 'x',
    46: 'c',
    47: 'v',
    48: 'b',
    49: 'n',
    50: 'm',
    51: 'comma',
    52: 'dot',
    53: 'slash',
    54: 'rightshift',
    56: 'leftalt',
    57: 'space',
    58: 'capslock',
    59: 'f1',
    60: 'f2',
    61: 'f3',
    62: 'f4',
    63: 'f5',
    64: 'f6',
    65: 'f7',
    66: 'f8',
    67: 'f9',
    68: 'f10',
    86: '102nd',
    87: 'f11',
    88: 'f12',
    97: 'rightctrl',
    99: 'sysrq',
    100: 'rightalt',
    103: 'up',
    105: 'left',
    106: 'right',
    108: 'down',
    110: 'insert',
    111: 'delete',
    114: 'volumedown',
    115: 'volumeup',
    125: 'leftmeta',
    140: 'calc',
}

shift_conversion = {
    '1': '!',
    '2': '"',
    '3': '§',
    '4': '$',
    '5': '%',
    '6': '&',
    '7': '/',
    '8': '(',
    '9': ')',
    '0': '=',
    'a': 'A',
    'b': 'B',
    'c': 'C',
    'd': 'D',
    'e': 'E',
    'f': 'F',
    'g': 'G',
    'h': 'H',
    'i': 'I',
    'j': 'J',
    'k': 'K',
    'l': 'L',
    'm': 'M',
    'n': 'N',
    'o': 'O',
    'p': 'P',
    'q': 'Q',
    'r': 'R',
    's': 'S',
    't': 'T',
    'u': 'U',
    'v': 'V',
    'w': 'W',
    'x': 'X',
    'y': 'Y',
    'z': 'Z',
    '+': '*',
    '<': '>',
    '-': '_',
    '#': '\'',
}

altgr_conversion = {
    '1': '¹',
    '2': '²',
    '3': '³',
    '4': '¼',
    '5': '$',
    '6': '¬',
    '7': '{',
    '8': '[',
    '9': ']',
    '0': '}',
    '<': '>',
}


def keycode_to_key(keycode: str):
    if keycode not in keycode_conversion:
        logging.warning('Tried to convert unknown keycode "%s"', keycode)
        return keycode
    return keycode_conversion[keycode]


def key_to_shift_key(key: str):
    return shift_conversion.get(key, key)


def key_to_alt_key(key: str):
    return altgr_conversion.get(key, key)
